app/Http/routes.php
<?php

Route::group(['as' => 'app::','middleware' => ['web']], function () {

    Route::get('/', ['as' => 'home', 'uses' => 'PagesController@index']);

    //Search Movie
    Route::get('/search', ['as' => 'movie.search', 'uses' => 'PagesController@search']);
    Route::get('/autocomplete', ['as' => 'movie.autocomplete', 'uses' => 'PagesController@autoComplete']);

    // Filter Movies by Genre, Year or Country
    Route::get('/browse-movies', ['as' => 'movie.filter.all', 'uses' => 'PagesController@filterAll']);
    Route::get('/year/{year}', ['as' => 'movie.filter.year', 'uses' => 'PagesController@filterYear']);
    Route::get('/genre/{genre}', ['as' => 'movie.filter.genre', 'uses' => 'PagesController@filterGenre']);
    Route::get('/country/{country}', ['as' => 'movie.filter.country', 'uses' => 'PagesController@filterCountry']);
    Route::get('/actor/{actor}', ['as' => 'movie.filter.actor', 'uses' => 'PagesController@filterActor']);
    Route::get('/director/{director}', ['as' => 'movie.filter.actor', 'uses' => 'PagesController@filterDirector']);

    // Show Movie
    Route::get('/movie/{title}', ['as' => 'movie.show', 'uses' => 'PagesController@show', 'middleware' => 'visits']);

});

// Route::get('/info', function ()
// {
//     $client = new \GuzzleHttp\Client(['base_uri' => 'https://api.openload.co/1/']);
//     $response = $client->get('file/ul?login=47139f294035aefd&key=FDJwOwGl');

//     $decoded = json_decode($response->getBody(), true);

//     dd($decoded);
// });

Route::group(['middleware' => ['web']], function () {

    // Authorization
    Route::get('/login',  ['as' => 'auth.login.form', 'uses' => 'Auth\SessionController@getLogin']);
    Route::post('/login', ['as' => 'auth.login.attempt', 'uses' => 'Auth\SessionController@postLogin']);
    Route::get('/logout', ['as' => 'auth.logout', 'uses' => 'Auth\SessionController@getLogout']);

    // Registration
    Route::get('register',  ['as' => 'auth.register.form', 'uses' => 'Auth\RegistrationController@getRegister']);
    Route::post('register', ['as' => 'auth.register.attempt', 'uses' => 'Auth\RegistrationController@postRegister']);

    // Activation
    Route::get('activate/{code}', ['as' => 'auth.activation.attempt', 'uses' => 'Auth\RegistrationController@getActivate']);
    Route::get('resend', ['as' => 'auth.activation.request', 'uses' => 'Auth\RegistrationController@getResend']);
    Route::post('resend', ['as' => 'auth.activation.resend', 'uses' => 'Auth\RegistrationController@postResend']);

    // Password Reset
    Route::get('password/reset/{code}', ['as' => 'auth.password.reset.form', 'uses' => 'Auth\PasswordController@getReset']);
    Route::post('password/reset/{code}', ['as' => 'auth.password.reset.attempt', 'uses' => 'Auth\PasswordController@postReset']);
    Route::get('password/reset', ['as' => 'auth.password.request.form', 'uses' => 'Auth\PasswordController@getRequest']);
    Route::post('password/reset', ['as' => 'auth.password.request.attempt', 'uses' => 'Auth\PasswordController@postRequest']);

    // Users
    Route::resource('users', 'UserController');

    // Roles
    Route::resource('roles', 'RoleController');

    // Dashboard
    Route::get('dashboard', ['as' => 'dashboard', 'uses' => function() {
        return view('centaur.dashboard');
    }]);

    Route::group(['middleware' => ['auth']], function () {
        
        // Movies
        Route::resource('movies', 'MovieController');
        Route::get('movies/search/autocomplete', 'MovieController@autoComplete');

        //Casts
        Route::resource('casts', 'CastController');
        Route::get('casts/create/autocomplete', 'CastController@autoComplete');
    });
});

resources/views/admin/movies/create.blade.php
@extends('Centaur::layout')

@section('title', 'Upload Movie')

@section('content')
<div class="page-header">
    <h1>Upload Movie</h1>
</div>
<div class="row">
    @include('partials.flash')
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-body"> 
                {!! Form::open(['route' => 'movies.store', 'files' => true]) !!}
                <fieldset>
                    <div class="form-group {{ ($errors->has('title')) ? 'has-error' : '' }}">
                        {!! Form::label('title', 'Title') !!}
                        {!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Movie Title']) !!}
                        {!! ($errors->has('title') ? $errors->first('title', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('genre')) ? 'has-error' : '' }}">
                        {!! Form::label('genre', 'Genre') !!}
                        {!! Form::select('genre[]', $genres, null, ['id' => 'genre_list', 'class' => 'form-control', 'multiple']) !!}
                        {!! ($errors->has('genre') ? $errors->first('genre', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('country_id')) ? 'has-error' : '' }}">
                        {!! Form::label('country_id', 'Country') !!}
                        {!! Form::select('country_id', $countries, null, ['id' => 'country_list', 'class' => 'multiple form-control', 'placeholder' => '']) !!}
                        {!! ($errors->has('country_id') ? $errors->first('country_id', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('year_id')) ? 'has-error' : '' }}">
                        {!! Form::label('year_id', 'Year') !!}
                        {!! Form::select('year_id', $years, null, ['id' => 'year_list', 'class' => 'form-control', 'placeholder' => '']) !!}
                        {!! ($errors->has('year_id') ? $errors->first('year_id', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('plot')) ? 'has-error' : '' }}">
                        {!! Form::label('plot', 'Plot') !!}
                        {!! Form::textarea('plot', null, ['class' => 'form-control', 'placeholder' => 'Movie Plot']) !!}
                        {!! ($errors->has('plot') ? $errors->first('plot', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('rating')) ? 'has-error' : '' }}">
                        {!! Form::label('rating', 'Rating') !!}
                        {!! Form::text('rating', null, ['class' => 'form-control', 'placeholder' => 'Movie Rating']) !!}
                        {!! ($errors->has('rating') ? $errors->first('rating', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('duration')) ? 'has-error' : '' }}">
                        {!! Form::label('duration', 'Duration') !!}
                        {!! Form::text('duration', null, ['class' => 'form-control', 'placeholder' => 'Movie Duration']) !!}
                        {!! ($errors->has('duration') ? $errors->first('duration', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-body">
                <fieldset>                    
                    <div class="form-group {{ ($errors->has('director')) ? 'has-error' : '' }}">
                        {!! Form::label('director', 'Director') !!}
                        {!! Form::select('director', $people, null, ['id' => 'director', 'class' => 'form-control', 'placeholder' => '']) !!}
                        {!! ($errors->has('director') ? $errors->first('director', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('cast')) ? 'has-error' : '' }}">
                        {!! Form::label('cast', 'Cast') !!}
                        {!! Form::select('cast[]', $people, null, ['id' => 'cast', 'class' => 'form-control', 'multiple']) !!}
                        {!! ($errors->has('cast') ? $errors->first('cast', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('image')) ? 'has-error' : '' }}">
                        {!! Form::label('image', 'Upload Image') !!}
                        {!! Form::file('image') !!}
                        <p class="help-block">Image Size: 175 x 260</p>
                        {!! ($errors->has('image') ? $errors->first('image', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('background')) ? 'has-error' : '' }}">
                        {!! Form::label('background', 'Upload Background Image') !!}
                        {!! Form::file('background') !!}
                        {!! ($errors->has('background') ? $errors->first('background', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('trailer')) ? 'has-error' : '' }}">
                        {!! Form::label('trailer', 'Trailer') !!}
                        {!! Form::text('trailer', null, ['class' => 'form-control', 'placeholder' => 'Movie Trailer: Url of the trailer']) !!}
                        {!! ($errors->has('trailer') ? $errors->first('trailer', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('path')) ? 'has-error' : '' }}">
                        {!! Form::label('path', 'Upload Movie') !!}
                        {!! Form::text('path', null, ['class' => 'form-control', 'placeholder' => 'Movie URL']) !!}
                        {!! ($errors->has('path') ? $errors->first('path', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group">
                        {!! Form::submit('Upload', ['class' => 'btn btn-lg btn-primary btn-block']) !!}
                    </div>
                </fieldset>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@stop

@section('footer')
    <script>
        $('#genre_list').select2({
          placeholder: "Select a genres",
          allowClear: true
        });
        $('#year_list').select2({
          placeholder: "Select Year...",
          allowClear: true
        });
        $('#country_list').select2({
          placeholder: "Select Country...",
          allowClear: true
        });
        $('#director').select2({
          placeholder: "Select director",
          allowClear: true
        });
        $('#cast').select2({
          placeholder: "Select casts",
          allowClear: true
        });
    </script>
@stop

resources/views/admin/movies/edit.blade.php
@extends('Centaur::layout')

@section('title', 'Movies')

@section('content')
<div class="page-header">
    <h1>Upload Movie</h1>
</div>
<div class="row"> 
    @include('partials.flash')
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-body"> 
                {!! Form::model($movie, ['method' => 'PATCH', 'route' => ['movies.update', $movie->id], 'files' => true]) !!}
                <fieldset>
                    <div class="form-group {{ ($errors->has('title')) ? 'has-error' : '' }}">
                        {!! Form::label('title', 'Title') !!}
                        {!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Movie Title']) !!}
                        {!! ($errors->has('title') ? $errors->first('title', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('genre')) ? 'has-error' : '' }}">
                        {!! Form::label('genre', 'Genre') !!}
                        {!! Form::select('genre_list[]', $genres, null, ['id' => 'genre_list', 'class' => 'form-control', 'multiple']) !!}
                        {!! ($errors->has('genre') ? $errors->first('genre', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('country_id')) ? 'has-error' : '' }}">
                        {!! Form::label('country_id', 'Country') !!}
                        {!! Form::select('country_id', $countries, null, ['id' => 'country_list', 'class' => 'multiple form-control', 'placeholder' => '']) !!}
                        {!! ($errors->has('country_id') ? $errors->first('country_id', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('year_id')) ? 'has-error' : '' }}">
                        {!! Form::label('year_id', 'Year') !!}
                        {!! Form::select('year_id', $years, null, ['id' => 'year_list', 'class' => 'form-control', 'placeholder' => '']) !!}
                        {!! ($errors->has('year_id') ? $errors->first('year_id', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('plot')) ? 'has-error' : '' }}">
                        {!! Form::label('plot', 'Plot') !!}
                        {!! Form::textarea('plot', null, ['class' => 'form-control', 'placeholder' => 'Movie Plot']) !!}
                        {!! ($errors->has('plot') ? $errors->first('plot', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('rating')) ? 'has-error' : '' }}">
                        {!! Form::label('rating', 'Rating') !!}
                        {!! Form::text('rating', null, ['class' => 'form-control', 'placeholder' => 'Movie Rating']) !!}
                        {!! ($errors->has('rating') ? $errors->first('rating', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('duration')) ? 'has-error' : '' }}">
                        {!! Form::label('duration', 'Duration') !!}
                        {!! Form::text('duration', null, ['class' => 'form-control', 'placeholder' => 'Movie Duration']) !!}
                        {!! ($errors->has('duration') ? $errors->first('duration', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-body">
                <fieldset>                    
                    <div class="form-group {{ ($errors->has('director')) ? 'has-error' : '' }}">
                        {!! Form::label('director', 'Director') !!}
                        {!! Form::select('director_list[]', $people, null, ['id' => 'director', 'class' => 'form-control', 'placeholder' => '']) !!}
                        {!! ($errors->has('director') ? $errors->first('director', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('cast')) ? 'has-error' : '' }}">
                        {!! Form::label('cast', 'Cast') !!}
                        {!! Form::select('cast_list[]', $people, null, ['id' => 'cast', 'class' => 'form-control', 'multiple']) !!}
                        {!! ($errors->has('cast') ? $errors->first('cast', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('image')) ? 'has-error' : '' }}">
                        {!! Form::label('image', 'Upload Poster Image') !!}
                        {!! Form::file('image') !!}
                        <p class="help-block">Image Size: 175 x 260</p>
                        {!! ($errors->has('image') ? $errors->first('image', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('background')) ? 'has-error' : '' }}">
                        {!! Form::label('background', 'Upload Background Image') !!}
                        {!! Form::file('background') !!}
                        {!! ($errors->has('background') ? $errors->first('background', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('trailer')) ? 'has-error' : '' }}">
                        {!! Form::label('trailer', 'Trailer') !!}
                        {!! Form::text('trailer', null, ['class' => 'form-control', 'placeholder' => 'Movie Trailer: Url of the trailer']) !!}
                        {!! ($errors->has('trailer') ? $errors->first('trailer', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group {{ ($errors->has('path')) ? 'has-error' : '' }}">
                        {!! Form::label('path', 'Upload Movie') !!}
                        {!! Form::text('path', null, ['class' => 'form-control', 'placeholder' => 'Movie URL']) !!}
                        {!! ($errors->has('path') ? $errors->first('path', '<p class="text-danger">:message</p>') : '') !!}
                    </div>
                    <div class="form-group">
                        {!! Form::submit('Modify', ['class' => 'btn btn-lg btn-warning btn-block']) !!}
                    </div>
                </fieldset>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@stop

@section('footer')
    <script>
        $('#genre_list').select2({
          placeholder: "Select a genres",
          allowClear: true
        });
        $('#year_list').select2({
          placeholder: "Select Year...",
          allowClear: true
        });
        $('#country_list').select2({
          placeholder: "Select Country...",
          allowClear: true
        });
        $('#director').select2({
          placeholder: "Select director",
          allowClear: true
        });
        $('#cast').select2({
          placeholder: "Select casts",
          allowClear: true
        });
    </script>
@stop

resources/views/admin/movies/index.blade.php
@extends('Centaur::layout')

@section('title', 'Movies')

@section('header')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.css" type="text/css" />
@stop

@section('content')
    
    @include('partials.flash')
    
    {!! Form::open(['method' => 'GET', 'action' => 'MovieController@index']) !!}
        {!! Form::text('term', null, ['id' => 'search-input', 'class' => 'form-control', 'placeholder' => 'Search movie archives...', 'tabindex' => 1]) !!}
    {!! Form::close() !!}    
    
    <div class="page-header">
        <div class='btn-toolbar pull-right'>
            <a class="btn btn-primary btn-lg" href="{{ url('movies/create') }}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                Upload Movie
            </a>
        </div>
        <h1>Movies</h1>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Title</th>
                            <th>Plot</th>
                            <th>Image</th>
                            <th>Uploaded Date</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($movies as $i => $movie)
                            <tr>
                                <td>{{ $i+1 }}</td>
                                <td>{{ str_limit($movie->title, 30) }}</td>
                                <td>{{ str_limit($movie->plot, 70) }}</td>
                                <td><img src="{{ asset('main/images/upload/movie/posters/' . $movie->image) }}" alt="{{ $movie->title }}" width="45" height="60"></td>
                                <td>{{ $movie->created_at->diffForHumans() }}</td>
                                <td>
                                    <a href="{{ route('movies.edit', $movie->id) }}" class="btn btn-default">
                                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                        Edit
                                    </a>
                                    <a href="{{ route('movies.destroy', $movie->id) }}" class="btn btn-danger" data-method="delete" data-token="{{ csrf_token() }}">
                                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                        Delete
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $movies->appends(Request::except('page'))->render() !!}                
            </div>
        </div>
    </div>
@stop

@section('footer')  
   <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
   <script>
        $('document').ready(function(){
            /* $('#search-input').attr('autocomplete', 'on');*/
            'use strict';

            $("#search-input").autocomplete({
            source: "{{ URL('movies/search/autocomplete') }}",
            type: "GET",
            minlength: 3,
            dataType: "json", 
                });
            });
    </script>
@stop